# mkdocs.yml — Root configuration for MkDocs (Material)
# This config builds an Arabic (RTL) docs site with clean LTR code blocks.

site_name: "مصطلحات برمجية"                       # Header title + <title>.
site_description: "Arabic tech terms with clean RTL + LTR code blocks"
site_url: ""                                       # Public URL (leave empty for local dev).
site_author: "Abdalkreem"

#Repo info — shows an icon/link in the header/footer (Material feature).
repo_name: "TechTerms"
repo_url: "https://github.com/akdue/TechTerms"

theme:
  name: material
  language: ar                                      # Arabic UI strings.
  #custom_dir: overrides         # ← مجلّد القوالب المخصّصة


  # ✅ Light/Dark palettes + toggle (respects system preference)
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: "تفعيل الوضع الداكن"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/white-balance-sunny
        name: "تفعيل الوضع الفاتح"

  features:
    - content.code.copy                             # Copy button on code blocks.
    - navigation.expand
    - navigation.top
    - navigation.indexes                            # يفعّل صفحات index.md للأقسام
    #- header.autohide           # ← يخفي الهيدر عند التمرير (Add For Beta)
    #- announce.dismiss          # ← يضيف زر إغلاق للإشعار (Add For Beta)
    #- toc.integrate                                 # يدمج جدول المحتويات في الصفحات
    
  icon:
    repo: fontawesome/brands/github                 # Repo icon in header.

# تمت إزالة nav بالكامل ليُبنى تلقائيًا من بنية docs/

# Keep Arabic text RTL while forcing code to LTR (see stylesheets/style.css).
extra_css:
  - stylesheets/style.css

# Plugins
plugins:
  - search
  - open-in-new-tab
  - meta

# Markdown extensions
markdown_extensions:
  - admonition                     # Callouts (!!! note/warning/tip)
  - attr_list                      # {: dir="ltr" } etc.
  - md_in_html                     # Parse MD inside simple HTML blocks
  - toc:
      permalink: true              # Anchor links for headings
  - tables
  - footnotes
  - pymdownx.superfences           # Robust fenced code blocks
  - pymdownx.highlight:            # Better syntax highlighting
      anchor_linenums: true
      linenums: false              # Set true to show line numbers
      auto_title: true

# Watch extra folders (so live-reload picks up CSS changes).
watch:
  - stylesheets

# Hide the "Made with Material for MkDocs" generator line and add social/footer.
extra:
  generator: false                 # <— Hides "Made with Material for MkDocs"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/akdue/TechTerms
      name: GitHub



# Optional footer copyright
copyright: "© 2025 Abdalkreem AbuAresh"

# Tips:
# - Serve locally (live reload): py -m mkdocs serve
# - Watch CSS explicitly (optional): py -m mkdocs serve -w stylesheets
# - Build production site: py -m mkdocs build
# - Deploy to GitHub Pages: py -m mkdocs gh-deploy --force