# mkdocs.yml — Root configuration for MkDocs (Material)
# Arabic RTL site + clean LTR code blocks + smart nav & plugins.

site_name: "مصطلحات برمجية"
site_description: "Arabic tech terms with clean RTL + LTR code blocks"
site_url: "https://akdue.github.io/TechTerms/"      # مهم لروابط السيو والـ canonical
site_author: "Abdalkreem"
use_directory_urls: true

# Repo info (يظهر زرّ عرض المصدر + تعديل الصفحة)
repo_name: "TechTerms"
repo_url: "https://github.com/akdue/TechTerms"
edit_uri: "edit/main/docs/"                          # زر "عدّل هذه الصفحة" يعمل مباشرة

theme:
  name: material
  language: ar
  features:
    # التنقّل وتجربة التصفّح
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.path                                 # breadcrumbs
    - navigation.sections                             # تقسيمات داخل الـ sidebar
    # دمج الفهرس في الشريط الجانبي (بدلاً من يمين الصفحة)
    #- toc.integrate
    #- toc.follow
    # مميزات البحث
    - search.suggest
    - search.highlight
    - search.share
    # الكود
    - content.code.copy
    - content.code.select
    - content.code.annotate                           # تعليقات مرقّمة على الأسطر
    # أزرار المصدر/التعديل
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default


# CSS مخصّص (لـ LTR للكود وخطوط أجمل)
extra_css:
  - stylesheets/style.css

# JS إضافي (اختياري لاحقًا)
# extra_javascript:
#   - javascripts/custom.js

# Plugins
plugins:
  - search:
      lang: ar
      separator: '[\s\-\.]+'
  - awesome-pages                         # ترتيب/تجميع تلقائي للـ nav من .pages
  - glightbox                             # Lightbox للصور
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
      locale: ar
  - minify:
      minify_html: true

# Markdown extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - tables
  - footnotes
  - abbr
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
      auto_title: true
  - pymdownx.details                      # ??? collapsible blocks (إظهار/إخفاء)
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.keys                         # ⌘K مثلًا
  - pymdownx.snippets                     # إدراج مقاطع مشتركة
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret

# Watch extra folders (so live-reload picks up CSS changes).
watch:
  - stylesheets


# إخفاء "Made with Material for MkDocs" + أيقونات اجتماعية
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/akdue/TechTerms
      name: GitHub

# حقوق
copyright: "© 2025 Abdalkreem AbuAresh"
